# Per-client infrastructure: secrets and future IAM rules.
# Driven by var.clients — add/remove access points declaratively.
# Pipeline schedules come from var.pipeline_schedules (generated by sync_schedules.py).

locals {
  # Flatten client -> access_points for per-connection resources
  access_points = merge([
    for client_key, client in var.clients : {
      for ap_key, ap in client.access_points :
      "${client_key}-${ap_key}" => merge(ap, {
        client = client_key
        ap     = ap_key
      })
    }
  ]...)
}

# --- Secrets: one per access point that has a secret_id ---

resource "google_secret_manager_secret" "client_sa" {
  for_each  = { for k, v in local.access_points : k => v if v.secret_id != null }
  secret_id = each.value.secret_id
  project   = var.project_id

  replication {
    auto {}
  }

  labels = {
    service = "granicus"
    client  = each.value.client
  }
}

resource "google_secret_manager_secret_iam_member" "engine_client_sa" {
  for_each  = google_secret_manager_secret.client_sa
  secret_id = each.value.secret_id
  project   = var.project_id
  role      = "roles/secretmanager.secretAccessor"
  member    = "serviceAccount:${google_service_account.engine.email}"
}

# --- Scheduler jobs: one per pipeline (from pipeline.yaml via sync script) ---

resource "google_cloud_scheduler_job" "pipeline" {
  for_each  = var.pipeline_schedules
  name      = "granicus-${replace(each.key, "_", "-")}"
  project   = var.project_id
  region    = var.region
  schedule  = each.value.schedule
  time_zone = "UTC"

  http_target {
    uri         = "${google_cloud_run_v2_service.engine.uri}/api/v1/pipelines/${each.key}/trigger"
    http_method = "POST"
    headers = {
      "Content-Type" = "application/json"
    }
    body = base64encode(jsonencode({ pipeline = each.key }))

    oidc_token {
      service_account_email = google_service_account.scheduler.email
      audience              = google_cloud_run_v2_service.engine.uri
    }
  }
}

# --- Future: cross-project IAM per access point ---
# When migrating from credential files to SA impersonation, add:
#
# resource "google_project_iam_member" "client_bq_data" {
#   for_each = local.access_points
#   project  = each.value.bq_project
#   role     = "roles/bigquery.dataEditor"
#   member   = "serviceAccount:${google_service_account.engine.email}"
# }
#
# resource "google_project_iam_member" "client_bq_jobs" {
#   for_each = local.access_points
#   project  = each.value.bq_project
#   role     = "roles/bigquery.jobUser"
#   member   = "serviceAccount:${google_service_account.engine.email}"
# }
