variable "project_id" {
  description = "GCP project ID for the Granicus platform"
  type        = string
  default     = "datadecode-platform"
}

variable "project_number" {
  description = "GCP project number for datadecode-platform"
  type        = string
  default     = "558164568"
}

variable "region" {
  description = "GCP region for all resources"
  type        = string
  default     = "us-central1"
}

variable "engine_service_name" {
  description = "Cloud Run service name for the Granicus engine"
  type        = string
  default     = "granicus-engine"
}

variable "ar_repository" {
  description = "Artifact Registry repository name"
  type        = string
  default     = "granicus"
}

variable "pipelines_bucket" {
  description = "GCS bucket for pipeline definitions and configs"
  type        = string
  default     = "granicus-analytehealth"
}

variable "github_org" {
  description = "GitHub organization for Workload Identity Federation"
  type        = string
  default     = "DataDecodeHQ"
}

variable "github_repo" {
  description = "GitHub repository name for WIF binding"
  type        = string
  default     = "granicus"
}

variable "cloud_run_memory" {
  description = "Cloud Run memory allocation"
  type        = string
  default     = "1Gi"
}

variable "cloud_run_cpu" {
  description = "Cloud Run CPU allocation"
  type        = string
  default     = "1"
}

variable "cloud_run_min_instances" {
  description = "Cloud Run minimum instance count"
  type        = number
  default     = 0
}

variable "cloud_run_max_instances" {
  description = "Cloud Run maximum instance count"
  type        = number
  default     = 3
}

variable "cloud_run_timeout" {
  description = "Cloud Run request timeout in seconds"
  type        = string
  default     = "3600s"
}

variable "schedule_prune" {
  description = "Cron schedule for nightly prune job"
  type        = string
  default     = "0 2 * * *"
}

# --- Client configuration ---
# Each client has a set of access points (BQ project connections).
# Each access point can have its own secret and future IAM rules.

variable "clients" {
  description = "Client definitions with their BQ access points"
  type = map(object({
    access_points = map(object({
      bq_project = string
      secret_id  = optional(string)
    }))
  }))

  default = {
    analytehealth = {
      access_points = {
        analytehealth = {
          bq_project = "api-project-178709533099"
          secret_id  = "granicus-sa-analytehealth"
        }
        paternitylabs = {
          bq_project = "paternitylab"
          secret_id  = "granicus-sa-paternitylabs"
        }
      }
    }
  }
}

# --- Pipeline schedules (generated by sync_schedules.py from pipeline.yaml) ---

variable "pipeline_schedules" {
  description = "Pipeline schedules synced from pipeline.yaml files"
  type = map(object({
    client   = string
    schedule = string
  }))
  default = {}
}
