package migrate

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func TestDetectVersion(t *testing.T) {
	tests := []struct {
		name    string
		content string
		want    string
	}{
		{
			name:    "no version field defaults to 0.2",
			content: "pipeline: my_pipeline\nassets: []\n",
			want:    "0.2",
		},
		{
			name:    "version 0.3 detected",
			content: "version: \"0.3\"\npipeline: my_pipeline\n",
			want:    "0.3",
		},
		{
			name:    "version with single quotes",
			content: "version: '0.3'\npipeline: my_pipeline\n",
			want:    "0.3",
		},
		{
			name:    "version without quotes",
			content: "version: 0.3\npipeline: my_pipeline\n",
			want:    "0.3",
		},
		{
			name:    "empty content defaults to 0.2",
			content: "",
			want:    "0.2",
		},
		{
			name:    "comment then no version defaults to 0.2",
			content: "# My pipeline\npipeline: foo\n",
			want:    "0.2",
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			got := DetectVersion([]byte(tt.content))
			if got != tt.want {
				t.Errorf("DetectVersion() = %q, want %q", got, tt.want)
			}
		})
	}
}

func TestMigrate_AlreadyCurrent(t *testing.T) {
	content := []byte("version: \"0.4\"\npipeline: foo\n")
	result, err := Migrate(content, "0.4")
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if !result.AlreadyCurrent {
		t.Error("expected AlreadyCurrent=true for 0.4 -> 0.4")
	}
	if len(result.Changes) != 0 {
		t.Errorf("expected no changes, got %d", len(result.Changes))
	}
}

func TestMigrate_02to04(t *testing.T) {
	content := []byte("pipeline: my_pipeline\nmax_parallel: 4\nconnections:\n  bq:\n    type: bigquery\nassets: []\n")
	result, err := Migrate(content, "0.2")
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}

	if result.FromVersion != "0.2" {
		t.Errorf("FromVersion = %q, want 0.2", result.FromVersion)
	}
	if result.ToVersion != "0.4" {
		t.Errorf("ToVersion = %q, want 0.4", result.ToVersion)
	}
	if len(result.Changes) == 0 {
		t.Error("expected at least one change")
	}

	output := string(result.Content)
	if !strings.Contains(output, `version: "0.4"`) {
		t.Errorf("output missing version 0.4 header:\n%s", output)
	}
	if strings.Contains(output, "connections:") {
		t.Errorf("output should not contain connections: after migration:\n%s", output)
	}
	if !strings.Contains(output, "resources:") {
		t.Errorf("output should contain resources: after migration:\n%s", output)
	}
	if !strings.Contains(output, "pipeline: my_pipeline") {
		t.Errorf("original content not preserved:\n%s", output)
	}
}

func TestMigrate_02to04_WithComments(t *testing.T) {
	content := []byte("# Pipeline config\n# Generated by hand\npipeline: my_pipeline\n")
	result, err := Migrate(content, "0.2")
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}

	output := string(result.Content)
	if !strings.Contains(output, `version: "0.4"`) {
		t.Errorf("output missing version 0.4 header:\n%s", output)
	}

	// Comments should be preserved
	if !strings.Contains(output, "# Pipeline config") {
		t.Errorf("comments not preserved:\n%s", output)
	}
}

func TestMigrate_03to04(t *testing.T) {
	content := []byte(`version: "0.3"
pipeline: test
connections:
  bq:
    type: bigquery
assets:
  - name: load
    type: python
    source: load.py
    destination_connection: bq
    source_connection: bq
sources:
  raw:
    connection: bq
    identifier: my_dataset
`)
	result, err := Migrate(content, "0.3")
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if result.ToVersion != "0.4" {
		t.Errorf("ToVersion = %q, want 0.4", result.ToVersion)
	}
	output := string(result.Content)
	if strings.Contains(output, "connections:") {
		t.Errorf("should not contain connections:\n%s", output)
	}
	if !strings.Contains(output, "resources:") {
		t.Errorf("should contain resources:\n%s", output)
	}
	if strings.Contains(output, "destination_connection:") {
		t.Errorf("should not contain destination_connection:\n%s", output)
	}
	if !strings.Contains(output, "destination_resource:") {
		t.Errorf("should contain destination_resource:\n%s", output)
	}
	if strings.Contains(output, "source_connection:") {
		t.Errorf("should not contain source_connection:\n%s", output)
	}
	if !strings.Contains(output, "source_resource:") {
		t.Errorf("should contain source_resource:\n%s", output)
	}
	// Source-level connection: should be renamed to resource:
	if strings.Contains(output, "    connection: bq") {
		t.Errorf("source-level connection: should be renamed to resource:\n%s", output)
	}
	if !strings.Contains(output, `version: "0.4"`) {
		t.Errorf("should contain version 0.4:\n%s", output)
	}
}

func TestMigrate_Idempotent(t *testing.T) {
	content := []byte("pipeline: my_pipeline\nassets: []\n")

	// First migration
	result1, err := Migrate(content, "0.2")
	if err != nil {
		t.Fatalf("first migration error: %v", err)
	}

	// Second migration on already-migrated content
	result2, err := Migrate(result1.Content, DetectVersion(result1.Content))
	if err != nil {
		t.Fatalf("second migration error: %v", err)
	}

	if !result2.AlreadyCurrent {
		t.Error("second migration should be a no-op (AlreadyCurrent=true)")
	}

	// Content should not change on second run
	if string(result2.Content) != string(result1.Content) {
		t.Errorf("idempotency violated:\nfirst:  %q\nsecond: %q", result1.Content, result2.Content)
	}
}

func TestAddVersionHeader_NoLeadingContent(t *testing.T) {
	content := []byte("pipeline: foo\n")
	result := addVersionHeader(content, "0.3")
	lines := strings.Split(string(result), "\n")
	if lines[0] != `version: "0.3"` {
		t.Errorf("first line = %q, want %q", lines[0], `version: "0.3"`)
	}
}

func TestAddVersionHeader_PreservesComments(t *testing.T) {
	content := []byte("# comment\npipeline: foo\n")
	result := addVersionHeader(content, "0.3")
	lines := strings.Split(string(result), "\n")
	if lines[0] != "# comment" {
		t.Errorf("first line = %q, want comment", lines[0])
	}
	if lines[1] != `version: "0.3"` {
		t.Errorf("second line = %q, want version", lines[1])
	}
}

func TestWriteBackup(t *testing.T) {
	dir := t.TempDir()
	configPath := filepath.Join(dir, "pipeline.yaml")
	content := []byte("pipeline: test\n")

	if err := os.WriteFile(configPath, content, 0644); err != nil {
		t.Fatal(err)
	}

	backupPath, err := WriteBackup(configPath)
	if err != nil {
		t.Fatalf("WriteBackup error: %v", err)
	}

	if !strings.HasSuffix(backupPath, ".bak") {
		t.Errorf("backup path %q should end with .bak", backupPath)
	}

	backupContent, err := os.ReadFile(backupPath)
	if err != nil {
		t.Fatalf("reading backup: %v", err)
	}

	if string(backupContent) != string(content) {
		t.Errorf("backup content mismatch")
	}
}
